# Generated by Django 5.0.2 on 2024-02-20 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0002_rename_pozitie_angajat_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='data_angajarii',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='hr',
            name='data_angajarii',
            field=models.DateField(auto_now_add=True),
        ),
    ]
