# Generated by Django 5.0.2 on 2024-02-20 18:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0003_alter_angajat_data_angajarii_alter_hr_data_angajarii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='data_angajarii',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='hr',
            name='data_angajarii',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
