# Generated by Django 5.0.2 on 2024-02-20 18:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0004_alter_angajat_data_angajarii_alter_hr_data_angajarii'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angajat',
            name='data_angajarii',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
        migrations.AlterField(
            model_name='hr',
            name='data_angajarii',
            field=models.DateField(default=datetime.date(2024, 2, 20)),
        ),
    ]
