# Generated by Django 5.0.2 on 2024-02-20 18:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0009_alter_angajat_data_angajarii_alter_hr_data_angajarii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='angajat',
            name='data_angajarii',
        ),
        migrations.AlterField(
            model_name='hr',
            name='data_angajarii',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
