# Generated by Django 5.0.2 on 2024-02-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0010_remove_angajat_data_angajarii_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='angajat',
            name='data_angajarii',
            field=models.DateField(default='YYYY-MM-DD'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hr',
            name='data_angajarii',
            field=models.DateField(),
        ),
    ]
