# Generated by Django 5.0.2 on 2024-02-20 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0011_angajat_data_angajarii_alter_hr_data_angajarii'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hr',
            name='departament',
        ),
    ]
