# Generated by Django 5.0.2 on 2024-02-23 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0017_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='description',
        ),
    ]
