# Generated by Django 5.0.2 on 2024-02-23 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0018_remove_company_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
    ]
