# Generated by Django 5.0.2 on 2024-02-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0024_alter_company_name_alter_owner_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner',
            old_name='nume',
            new_name='owner_name',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee'), ('hr', 'HR')], max_length=10),
        ),
    ]
