# Generated by Django 5.0.2 on 2024-02-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0025_rename_nume_owner_owner_name_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='owner_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
