# Generated by Django 5.0.2 on 2024-03-05 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0027_alter_owner_company_alter_owner_owner_name_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='departament',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='data_angajarii',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='hr',
            old_name='pozitie',
            new_name='position',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='owner_name',
        ),
        migrations.AddField(
            model_name='hr',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hr', to='worktimemanager.company'),
        ),
        migrations.AddField(
            model_name='owner',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='owner',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='worktimemanager.company'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('hr', 'HR'), ('employee', 'Employee')], max_length=10),
        ),
    ]
