# Generated by Django 5.0.2 on 2024-03-05 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0029_alter_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departament',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='zile_libere',
            new_name='free_days',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='data_angajarii',
            new_name='hire_date',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='pozitie',
            new_name='position',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ore_lucrate',
            new_name='working_hours',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='worktimemanager.company'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
