# Generated by Django 5.0.2 on 2024-03-05 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0030_rename_departament_employee_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='company',
        ),
        migrations.DeleteModel(
            name='HR',
        ),
    ]
