# Generated by Django 5.0.2 on 2024-03-05 21:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0031_remove_employee_company_delete_hr'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='worktimemanager.company'),
        ),
        migrations.AlterField(
            model_name='company',
            name='founded_date',
            field=models.DateField(verbose_name='Data înființării'),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.CharField(max_length=255, verbose_name='Industria'),
        ),
    ]
