# Generated by Django 5.0.2 on 2024-03-05 21:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0033_alter_employee_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='department',
            new_name='departament',
        ),
    ]
