# Generated by Django 5.0.2 on 2024-03-05 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0034_rename_department_employee_departament'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='departament',
            new_name='department',
        ),
    ]
