# Generated by Django 5.0.2 on 2024-03-09 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0037_employee_address_employee_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
