# Generated by Django 5.0.2 on 2024-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0040_employee_is_employee_hr_is_hr_owner_is_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('hr', 'HR'), ('employee', 'Employee'), ('visitor', 'Visitor')], default='visitor', max_length=10),
        ),
    ]
