# Generated by Django 5.0.2 on 2024-03-22 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0042_workschedule_is_approved_workschedule_is_leave_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={'verbose_name': 'Program de lucru', 'verbose_name_plural': 'Programe de lucru'},
        ),
        migrations.RemoveField(
            model_name='employee',
            name='shift_type',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='is_leave',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='leave_description',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='leave_type',
        ),
        migrations.AddField(
            model_name='leave',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='Leave Approved'),
        ),
        migrations.AddField(
            model_name='leave',
            name='is_leave',
            field=models.BooleanField(default=False, verbose_name='Is on Leave'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_description',
            field=models.TextField(blank=True, null=True, verbose_name='Leave Description'),
        ),
        migrations.AddField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('AN', 'Annual Leave'), ('SI', 'Sick Leave'), ('UP', 'Unpaid Leave'), ('MA', 'Maternity Leave'), ('PA', 'Paternity Leave'), ('ST', 'Study Leave')], max_length=2, null=True, verbose_name='Type of Leave'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='break_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='overtime_hours',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=4),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='shift_type',
            field=models.CharField(choices=[('day', 'Zi'), ('night', 'Noapte')], max_length=10, null=True),
        ),
    ]
