# Generated by Django 5.0.2 on 2024-03-22 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0043_alter_workschedule_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workschedule',
            options={},
        ),
    ]
