# Generated by Django 5.0.2 on 2024-03-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0044_alter_workschedule_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='break_end_time',
            new_name='break_time',
        ),
        migrations.RemoveField(
            model_name='workschedule',
            name='break_start_time',
        ),
    ]
