# Generated by Django 5.0.2 on 2024-03-22 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0045_rename_break_end_time_workschedule_break_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='break_time',
        ),
    ]
