# Generated by Django 5.0.2 on 2024-03-27 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0046_remove_workschedule_break_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='employee',
            new_name='employee_user_id',
        ),
    ]
