# Generated by Django 5.0.2 on 2024-03-27 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0047_rename_employee_workschedule_employee_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='employee_user_id',
            new_name='employee_user',
        ),
    ]
