# Generated by Django 5.0.2 on 2024-03-28 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0048_rename_employee_user_id_workschedule_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='employee_user',
            new_name='user_id',
        ),
    ]
