# Generated by Django 5.0.2 on 2024-03-28 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0049_rename_employee_user_workschedule_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workschedule',
            old_name='user_id',
            new_name='user',
        ),
    ]
