# Generated by Django 5.0.2 on 2024-03-29 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0050_rename_user_id_workschedule_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workschedule',
            name='shift_type',
        ),
        migrations.AlterField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='worktimemanager.employee'),
        ),
    ]
