# Generated by Django 5.0.2 on 2024-03-29 08:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0051_remove_workschedule_shift_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='user',
            field=models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='work_schedules', to='worktimemanager.employee'),
        ),
    ]
