# Generated by Django 5.0.2 on 2024-03-30 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0052_alter_workschedule_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='leave',
            old_name='employee',
            new_name='user',
        ),
    ]
