# Generated by Django 5.0.2 on 2024-03-30 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0054_alter_leave_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leave',
            name='reason',
        ),
        migrations.AddField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('AC', 'Acceptat'), ('RE', 'Refuzat'), ('PE', 'În așteptare')], default='PE', max_length=2, verbose_name='Leave Status'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='leave_type',
            field=models.CharField(blank=True, choices=[('AN', 'Concediu Anual'), ('SI', 'Concediu Medical'), ('UP', 'Concediu Fără Plată'), ('MA', 'Concediu Maternitate'), ('PA', 'Concediu Paternitate'), ('ST', 'Concediu de Studii')], max_length=2, null=True, verbose_name='Type of Leave'),
        ),
    ]
