# Generated by Django 5.0.2 on 2024-04-18 10:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0056_feedbackform_feedbackquestion_employeefeedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefeedback',
            name='response',
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='response_type',
            field=models.CharField(choices=[('text', 'Text'), ('rating', 'Rating'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=50),
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='score',
            field=models.IntegerField(default=0, help_text='Punctajul răspunsului'),
        ),
        migrations.CreateModel(
            name='FeedbackResponseOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=255)),
                ('score', models.IntegerField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='worktimemanager.feedbackquestion')),
            ],
        ),
    ]
