# Generated by Django 5.0.2 on 2024-04-18 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0057_remove_employeefeedback_response_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefeedback',
            name='response_type',
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worktimemanager.feedbackresponseoption'),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='rating_scale',
            field=models.IntegerField(blank=True, help_text='Scara de rating, de exemplu, 1-5', null=True),
        ),
        migrations.AddField(
            model_name='feedbackquestion',
            name='response_type',
            field=models.CharField(choices=[('text', 'Text'), ('rating', 'Rating'), ('multiple_choice', 'Multiple Choice')], default='text', max_length=50),
        ),
    ]
