# Generated by Django 5.0.2 on 2024-04-18 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0058_remove_employeefeedback_response_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefeedback',
            name='action_taken',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='hr_review_status',
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='action_taken',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feedbackform',
            name='hr_review_status',
            field=models.CharField(choices=[('pending', 'În așteptare'), ('reviewed', 'Revizuit'), ('action_required', 'Acțiune necesară')], default='pending', max_length=50, verbose_name='Status revizuire HR'),
        ),
    ]
