# Generated by Django 5.0.2 on 2024-04-18 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0059_remove_employeefeedback_action_taken_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefeedback',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='selected_responses', to='worktimemanager.feedbackresponseoption'),
        ),
    ]
