# Generated by Django 5.0.2 on 2024-04-18 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0060_alter_employeefeedback_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeefeedback',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employeefeedback',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='worktimemanager.employee'),
        ),
    ]
