# Generated by Django 5.0.2 on 2024-04-18 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0063_remove_employeefeedback_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefeedback',
            name='score',
        ),
        migrations.AddField(
            model_name='employeefeedback',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Scorul total pentru acest feedback'),
        ),
    ]
