# Generated by Django 5.0.2 on 2024-04-18 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0064_remove_employeefeedback_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeefeedback',
            name='question',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='response',
        ),
        migrations.RemoveField(
            model_name='employeefeedback',
            name='selected_option',
        ),
        migrations.CreateModel(
            name='FeedbackResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.TextField(blank=True, null=True)),
                ('score', models.IntegerField(default=0)),
                ('feedback', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_responses', to='worktimemanager.employeefeedback')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='worktimemanager.feedbackquestion')),
                ('selected_option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='worktimemanager.feedbackresponseoption')),
            ],
        ),
    ]
