# Generated by Django 5.0.2 on 2024-04-18 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0065_remove_employeefeedback_question_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackform',
            name='action_taken',
        ),
    ]
