# Generated by Django 5.0.2 on 2024-04-18 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0067_alter_employeefeedback_date_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedbackresponse',
            name='feedback',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='worktimemanager.employeefeedback'),
        ),
    ]
