# Generated by Django 5.0.2 on 2024-04-23 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0068_alter_feedbackresponse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackquestion',
            name='importance',
            field=models.IntegerField(default=1, help_text='Importanț'),
        ),
    ]
