# Generated by Django 5.0.2 on 2024-04-25 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0069_feedbackquestion_importance'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='training',
            name='duration',
            field=models.DurationField(default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AddField(
            model_name='training',
            name='enrollment_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='status',
            field=models.CharField(choices=[('planned', 'Planificat'), ('in_progress', 'În progres'), ('completed', 'Completat'), ('canceled', 'Anulat')], default='planned', max_length=50),
        ),
    ]
