# Generated by Django 5.0.2 on 2024-04-25 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0070_training_capacity_training_duration_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='employee',
            field=models.ManyToManyField(blank=True, related_name='trainings', to='worktimemanager.employee'),
        ),
    ]
