# Generated by Django 5.0.2 on 2024-04-26 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0073_trainingparticipant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainingparticipant',
            name='department',
        ),
    ]
