# Generated by Django 5.0.2 on 2024-04-26 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0074_remove_trainingparticipant_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='employee',
        ),
        migrations.AddField(
            model_name='training',
            name='participants',
            field=models.ManyToManyField(blank=True, related_name='trainings', through='worktimemanager.TrainingParticipant', to='worktimemanager.employee'),
        ),
        migrations.AlterField(
            model_name='trainingparticipant',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_participants', to='worktimemanager.training'),
        ),
    ]
