# Generated by Django 5.0.2 on 2024-04-28 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0075_remove_training_employee_training_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hr',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HR', to='worktimemanager.company'),
        ),
    ]
