# Generated by Django 5.0.2 on 2024-05-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0076_alter_hr_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workschedule',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
