# Generated by Django 5.0.2 on 2024-05-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0079_remove_notification_timestamp_notification_sender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workschedule',
            name='public_holidays',
            field=models.BooleanField(default=False, verbose_name='Public Holiday'),
        ),
        migrations.AddField(
            model_name='workschedule',
            name='work_history_details',
            field=models.JSONField(default=dict, verbose_name='Work history details'),
        ),
    ]
