# Generated by Django 5.0.2 on 2024-05-08 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0080_workschedule_public_holidays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='leaves_history_details',
            field=models.JSONField(default=dict, verbose_name='Leaves history details'),
        ),
    ]
