# Generated by Django 5.0.2 on 2024-05-09 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0081_leave_leaves_history_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='duration',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=4, verbose_name='Duration in Days'),
        ),
    ]
