# Generated by Django 5.0.2 on 2024-05-13 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0084_alter_employeefeedback_total_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeefeedback',
            name='total_score',
            field=models.IntegerField(default=0, help_text='Scorul total pentru acest feedback'),
        ),
        migrations.AlterField(
            model_name='feedbackresponseoption',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
