# Generated by Django 5.0.2 on 2024-05-15 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0086_alter_employeefeedback_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('work_schedule', 'Orar de Lucru'), ('leave', 'Concediu'), ('feedback', 'Feedback'), ('training', 'Training'), ('custom', 'Personalizat')], default='custom', max_length=20),
        ),
    ]
