# Generated by Django 5.0.2 on 2024-05-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0087_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('leave', 'Leave Type'), ('work_schedule', 'Work Schedule Type'), ('private', 'Private Type'), ('feedback', 'Feedback Type'), ('training', 'Training Type')], max_length=50),
        ),
    ]
