# Generated by Django 5.0.2 on 2024-05-16 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0089_privateevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedbackform',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
    ]
