# Generated by Django 5.0.2 on 2024-05-16 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0091_notification_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='notifications_sent',
            field=models.BooleanField(default=False),
        ),
    ]
