# Generated by Django 5.0.2 on 2024-05-16 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0093_leave_last_approved_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='duration_days',
        ),
        migrations.AlterField(
            model_name='leave',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='leave',
            name='last_approved_status',
            field=models.BooleanField(default=False),
        ),
    ]
