# Generated by Django 5.0.2 on 2024-05-16 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0095_training_duration_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='duration_days',
        ),
    ]
