# Generated by Django 5.0.2 on 2024-05-20 11:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0101_alter_training_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='hr',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='email',
            field=models.EmailField(db_index=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='telephone_number',
            field=models.CharField(max_length=100, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$')]),
        ),
    ]
