# Generated by Django 5.0.2 on 2024-05-21 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0102_hr_address_hr_email_hr_hire_date_hr_telephone_number'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='hr',
            options={'ordering': ['user']},
        ),
    ]
