# Generated by Django 5.0.2 on 2024-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worktimemanager', '0103_alter_employee_options_alter_hr_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hr',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
